#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'nonDivisibleSubset' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER k
#  2. INTEGER_ARRAY s
#
from itertools import permutations
def nonDivisibleSubset(k, s):
    f = [0]*k
    for i in range(len(s)):
        f[s[i] % k] += 1
    r = min(f[0],1)
    for i in range(1,(k//2)+1):
        if i != k-i:
            r += max(f[i],f[k-i])
        else:
            r += min(f[i],1)
    return r
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    s = list(map(int, input().rstrip().split()))

    result = nonDivisibleSubset(k, s)

    fptr.write(str(result) + '\n')

    fptr.close()
