#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pangrams' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def pangrams(s):
    k = []
    for i in s:
        if i == " ":
            continue
        elif i.lower() not in k:
            k.append(i.lower())
    if len(k)==26:
        return "pangram"
    else:
        return "not pangram"
        
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = pangrams(s)

    fptr.write(result + '\n')

    fptr.close()
