#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'quickSort' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def quickSort(arr):
    l = []
    e = []
    r = []
    p = arr[0]
    for i in range(1,len(arr)):
        if arr[i] >p:
            r.append(arr[i])
        elif arr[i]<p:
            l.append(arr[i])
        elif arr[i]==p:
            e.append(arr[i])
    e.append(p)
    return l+e+r
    
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = quickSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
