#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'separateNumbers' function below.
#
# The function accepts STRING s as parameter.
#

def separateNumbers(s):
    if len(s)==1:
        print("NO")
        return 
    else:
        for i in range(1,(len(s)//2) + 1):
            g = s[:i]
            p = int(g)
            while len(g) < len(s):
                nx = p+1
                g = g + str(nx)
                p = nx
            if g==s:
                print("YES",s[:i])
                return 
        print("NO")
                
    # Write your code here

if __name__ == '__main__':
    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        separateNumbers(s)
