#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'minimumNumber' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. STRING password
#

def minimumNumber(n, password):
    spl = "!@#$%^&*()-+"
    l = [0,0,0,0]
    for i in password:
        if i.islower():
            l[0] =1
        elif i.isupper():
            l[1]=1
        elif i.isdigit():
            l[2]=1
        elif i in spl:
            l[3]=1
    return max(6-n,4-sum(l))
    
    
    
    
    
    # Return the minimum number of characters to make the password strong

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    password = input()

    answer = minimumNumber(n, password)

    fptr.write(str(answer) + '\n')

    fptr.close()
