#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gridSearch' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING_ARRAY G
#  2. STRING_ARRAY P
#

def check(G,P,i,j):
    pr = len(P)
    pc = len(P[0])
    for row in range(0,pr):
        if P[row] != G[i+row][j:j+pc]:
            return 0
    return 1
    
def gridSearch(G, P):
    gr = len(G)
    gc = len(G[0])
    pr = len(P)
    pc = len(P[0])
    for i in range(0,gr-pr+1):
        for j in range(0,gc-pc+1):
            pval = P[0][0]
            if G[i][j] == pval:
                res = check(G,P,i,j)
                if res ==1:
                    return "YES"
    return "NO"

    
                
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        first_multiple_input = input().rstrip().split()

        R = int(first_multiple_input[0])

        C = int(first_multiple_input[1])

        G = []

        for _ in range(R):
            G_item = input()
            G.append(G_item)

        second_multiple_input = input().rstrip().split()

        r = int(second_multiple_input[0])

        c = int(second_multiple_input[1])

        P = []

        for _ in range(r):
            P_item = input()
            P.append(P_item)

        result = gridSearch(G, P)

        fptr.write(result + '\n')

    fptr.close()
